nelmio_api_doc:
    documentation:
        info:
            title: Hub Support
            description: This is an awesome app for management ticket support !
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

        security:
            - Bearer: []
    areas:
        disable_default_routes: true
        path_patterns:
            - ^/api(?!/doc$)
