services:
  frontend:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"   # 👈 Changed host port to 5173, container still uses nginx on 80
    restart: unless-stopped