# API Routes
api:
    resource:
        path: ../src/Infrastructure/Controller/Api/
        namespace: App\Infrastructure\Controller\Api
    type: attribute
    prefix: '/api'

# Swagger UI route
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
